makefile, src/docs/services/dotnet.md, src/services/dotnet/webapi/makefile
=> feat: dotnet multi-cloud commands

src/docs/clouds.md, src/docs/contribute.md
=> docs: heroku shallow clones

mkdocs.yml, src/docs/assets/stylesheets/extra.css, src/docs/contribute.md, src/docs/index.md
=> docs: diagrams

mkdocs.yml, src/docs/assets/stylesheets/extra.css, src/mkdocs/Dockerfile
=> chore: remove older and unused mkdocs-mermaid2-plugin

src/docs/index.md
=> docs: heroku abstractions

src/docs/devops.md
=> docs: devops status badges

src/docs/contribute.md, src/docs/license.md
docs: update contribution links
=> docs: update open source links

src/docs/license.md
=> docs: docker open source

src/docs/services/dotnet.md
=> fix: dotnet workflow file name

src/services/nodejs/expressjs/webapi/deploy/aws/makefile, src/services/nodejs/expressjs/webapi/deploy/azure/makefile
=> chore: update cloud cli docker image references

.github/workflows/docker_heroku-cli.yml, src/docker/heroku-cli/Dockerfile, src/docker/heroku-cli/makefile, src/docs/clouds.md, src/docs/services/nodejs-expressjs.md, src/services/nodejs/expressjs/webapi/deploy/azure/uninstall.sh, src/services/nodejs/expressjs/webapi/deploy/gcloud/.env.example, src/services/nodejs/expressjs/webapi/deploy/gcloud/logs.sh, src/services/nodejs/expressjs/webapi/deploy/gcloud/uninstall, src/services/nodejs/expressjs/webapi/deploy/heroku/.env.example, src/services/nodejs/expressjs/webapi/deploy/heroku/install.sh, src/services/nodejs/expressjs/webapi/deploy/heroku/login.sh, src/services/nodejs/expressjs/webapi/deploy/heroku/logs.sh, src/services/nodejs/expressjs/webapi/deploy/heroku/makefile, src/services/nodejs/expressjs/webapi/deploy/heroku/uninstall, src/services/nodejs/expressjs/webapi/makefile
=> chore: refactor nodejs heroku and multi-cloud

src/docs/assets/stylesheets/extra.css, src/docs/contribute.md
Updated  './src/docs/assets/stylesheets/extra.css' and './src/docs/contribute.md' files.
**NOTE:** 
I did not test the changes with make and docker since I am yet to download and experiment with them.
=> Updated './src/docs/assets/stylesheets/extra.css' and './src/docs/contribute.md' files

makefile, mkdocs.yml, src/docs/clouds.md, src/services/dotnet/webapi/.dockerignore, src/services/dotnet/webapi/Dockerfile, src/services/dotnet/webapi/Program.cs, src/services/dotnet/webapi/docker-compose.yml, src/services/dotnet/webapi/makefile, src/services/dotnet/webapi/test-local-tools.sh, src/services/jvm/java/springboot/webapi/.dockerignore, src/services/jvm/java/springboot/webapi/docker-compose.yml, src/services/jvm/java/springboot/webapi/docker/Dockerfile, src/services/jvm/java/springboot/webapi/makefile, src/services/jvm/java/springboot/webapi/test-local-tools.sh, src/services/jvm/kotlin/springboot/webapi/.dockerignore, src/services/jvm/kotlin/springboot/webapi/docker-compose.yml, src/services/jvm/kotlin/springboot/webapi/docker/Dockerfile, src/services/jvm/kotlin/springboot/webapi/makefile, src/services/jvm/kotlin/springboot/webapi/test-local-tools.sh, src/services/nodejs/expressjs/webapi/.dockerignore, src/services/nodejs/expressjs/webapi/docker/Dockerfile
=> test: local dev_tool execution

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, src/docs/contribute.md
[x] I have read the Contributor Guide
[x] I have added the Create PR Template and updated contribute guide step -13. 
[x] Screenshots attached  - See below.
[x ] commit message - docs: #61 Create PR template Issue and signed off
.
=> docs: #61 Create PR template Issue - Added a PR template

src/docker/aws-cli/Dockerfile, src/docker/aws-cli/makefile
=> feat(docker/aws-cli): yum-utils

.github/workflows/documentation.yml
=> fix: do not run documentation pr for forks

.github/workflows/documentation.yml
=> fix: do not generate auto-doc pr for forks

.github/workflows/documentation.yml
=> chore: refactor strings as vars

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/workflows/documentation.yml
=> chore: replace individuals with teams

src/services/dotnet/webapi/makefile
=> chore: clean up old cloud make vars

.github/workflows/documentation.yml
=> chore: use system account pat for team-reviewers

.github/workflows/documentation.yml, mkdocs.yml, src/docs/clouds.md, src/docs/compare.md, src/docs/index.md, src/puppeteer/screenshots.js
=> docs: cloud comparisons

src/docs/clouds.md
=> docs: multi-cloud
